spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.72.132
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8201
eureka:
  client:
   service-url:
     defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
       eureka.instance.lease-renewal-interval-in-seconds